<a href="https://colab.research.google.com/github/SydneySmoothvile/AL_ML_grp_task/blob/main/AL_ML_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
import pandas as pd #dataset library
import numpy as np #linear algebra library

In [130]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform,normal

Hyperparameters

In [131]:
batch_size=2

In [132]:
data_dict={'Day 1' : [30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [133]:
data=pd.DataFrame(data_dict)

In [134]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [135]:
X=data.drop('Target', axis=1)
y=data['Target']

In [136]:
X_trans=Normalizer(norm='max').fit_transform(X)

In [137]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [138]:
y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [139]:
y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [140]:
X_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

ANN Model from Scratch

In [141]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [142]:
uniform(-1,1,(3,2))

array([[-0.12218723, -0.17002374],
       [-0.93348395, -0.54137985],
       [ 0.55358676,  0.94890172]])

In [143]:
weight_1=uniform(-1,1,(3,2)) #shape of 3 by 2
weight_2=uniform(-1,1,(2,1))

In [144]:
X=X_trans

In [145]:
X[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [146]:
output_1=X[0:batch_size]@weight_1
output_1

array([[ 0.18539926, -0.89693717],
       [-0.22063046, -0.44432535]])

In [147]:
act_output_1=sigmoid(output_1).numpy()
act_output_1

array([[0.54621751, 0.28968032],
       [0.44506505, 0.39071081]])

In [148]:
final_output=act_output_1@weight_2
final_output

array([[-0.65547862],
       [-0.62940216]])

In [149]:
y_true=y[0][0:batch_size]
y_pred=final_output.T

In [150]:
y_true

array([0.28571429, 0.21428571])

In [151]:
y_pred

array([[-0.65547862, -0.62940216]])

Computing Mean Squared Error

In [152]:
mse(y_true,y_pred).numpy()

array([0.79882666])